# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(default='test123', help_text='Please do not select white spaces', max_length=20, unique=True, verbose_name='Please Enter your Unique Username')),
                ('Password', models.CharField(default='Pass123', max_length=15)),
                ('Total_Property', models.PositiveIntegerField(default=0)),
                ('Email', models.EmailField(max_length=40, unique=True)),
                ('Contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Contract_date', models.DateTimeField(auto_now_add=True)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
