# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
