# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
