# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190711_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
