# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190711_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_consumption', models.FloatField()),
                ('current_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_property_cumulative', models.FloatField()),
                ('block_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('current_balance', models.FloatField(default=0)),
                ('Associated_floor', models.CharField(max_length=60)),
                ('which_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='which_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Room'),
        ),
    ]
